#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy Main.Api to a VPS, behind Caddy, over real HTTPS.
# ──────────────────────────────────────────────────────────────────────────

REPO_URL="https://github.com/herveblondeau/Workflow.git"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

TOTAL_STAGES=4

banner "Main.Api: deploy to a VPS"
say "This only deploys workflow-api, bound to 127.0.0.1:8080 on the VPS."
say "Fronting it with a reverse proxy (nginx, Caddy, whatever you already run) and TLS is on you."

# ── Stage 1: SSH access ─────────────────────────────────────────────────────
stage "SSH access"
say "This stage clones/updates the repo on the VPS and starts the containers over SSH."
ask VPS_SSH "SSH target for the VPS (user@host):"
step "Checking SSH connectivity..."
if ssh -o BatchMode=yes -o ConnectTimeout=5 "$VPS_SSH" true 2>/dev/null; then
  printf '  %s✓ connected%s to %s\n' "$GREEN" "$RESET" "$VPS_SSH"
else
  warn "couldn't reach $VPS_SSH over SSH (key-based auth required). Fix access, then re-run."
  exit 1
fi
write_env VPS_SSH "$VPS_SSH"

# ── Stage 2: Secrets ─────────────────────────────────────────────────────
stage "Secrets"
say "API_KEY is required: it's what filigrane (and any future client) sends as X-Api-Key."
current_key=$(_existing API_KEY || true)
if [[ -z "$current_key" ]] && confirm "Generate a random API_KEY?"; then
  API_KEY=$(openssl rand -hex 32)
  printf '  %s✓ generated%s a new API_KEY\n' "$GREEN" "$RESET"
else
  ask_secret API_KEY "Paste (or set) the API_KEY:"
fi
write_env API_KEY "$API_KEY"

say "AI provider keys are optional (missing ones are silently skipped). Press Enter to skip any."
for pair in "OPENAI_API_KEY:OPENAI_DEFAULT_MODEL" "ANTHROPIC_API_KEY:ANTHROPIC_DEFAULT_MODEL" "GEMINI_API_KEY:GEMINI_DEFAULT_MODEL" "OPENROUTER_API_KEY:OPENROUTER_DEFAULT_MODEL"; do
  key_var="${pair%%:*}"
  model_var="${pair##*:}"
  ask_secret "$key_var" "$key_var (optional):"
  if [[ -n "${!key_var}" ]]; then
    ask "$model_var" "$model_var (e.g. a default model id):"
    write_env "$key_var" "${!key_var}"
    write_env "$model_var" "${!model_var}"
  fi
done

# ── Stage 3: Deploy ─────────────────────────────────────────────────────
stage "Deploy"
say "This clones/pulls the repo on the VPS and runs docker compose up -d --build."
if ! confirm "Ready to deploy to $VPS_SSH?"; then
  warn "skipped deploy; re-run this wizard when ready (values already saved)"
else
  step "Checking docker is available on the VPS..."
  if ! ssh "$VPS_SSH" 'command -v docker >/dev/null && docker compose version >/dev/null' 2>/dev/null; then
    warn "docker (with the compose plugin) isn't available on $VPS_SSH."
    note "Install it first: https://docs.docker.com/engine/install/, then re-run this wizard."
    exit 1
  fi
  step "Cloning/updating the repo on the VPS..."
  ssh "$VPS_SSH" "if [ -d workflow/.git ]; then cd workflow && git pull; else git clone $REPO_URL workflow; fi"
  step "Copying deploy/.env to the VPS..."
  scp "$ENV_FILE" "$VPS_SSH:workflow/deploy/.env" >/dev/null
  step "Starting containers (docker compose up -d --build)..."
  ssh "$VPS_SSH" 'cd workflow/deploy && docker compose --env-file .env up -d --build'
  printf '  %s✓ deployed%s\n' "$GREEN" "$RESET"
fi

# ── Stage 4: Verify ─────────────────────────────────────────────────────
stage "Verify"
say "Checking that Main.Api is reachable on the VPS's loopback interface."
status=""
for _ in $(seq 1 12); do
  status=$(ssh "$VPS_SSH" "curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8080/api/system/status" 2>/dev/null || true)
  [[ "$status" == "204" ]] && break
  sleep 5
done
if [[ "$status" == "204" ]]; then
  printf '  %s✓ 127.0.0.1:8080/api/system/status -> 204 (on %s)%s\n' "$GREEN" "$VPS_SSH" "$RESET"
else
  warn "got HTTP $status from 127.0.0.1:8080/api/system/status on $VPS_SSH"
  note "check: ssh $VPS_SSH 'cd workflow/deploy && docker compose logs'"
fi

finish
note "deploy/.env on this machine now holds everything needed to re-run this wizard idempotently."
note "repo used on the VPS: $REPO_URL"
note "not done yet: point your reverse proxy at 127.0.0.1:8080 on the VPS and terminate TLS there."
unset SCRIPT_DIR
